using System;
using System.Collections.Generic;

namespace PartnershipAgent.Core.Models;

/// <summary>
/// Model that represents the state and data passed between process steps.
/// </summary>
public class ProcessModel
{
    /// <summary>
    /// Unique identifier for the processing session.
    /// </summary>
    public Guid SessionId { get; set; }

    /// <summary>
    /// The current user input being processed.
    /// </summary>
    public string Input { get; set; } = string.Empty;

    /// <summary>
    /// The initial user prompt that started the conversation.
    /// </summary>
    public string InitialPrompt { get; set; } = string.Empty;

    /// <summary>
    /// Entities extracted from the user input.
    /// </summary>
    public List<ExtractedEntity> ExtractedEntities { get; set; } = [];

    /// <summary>
    /// Documents found relevant to the user query.
    /// </summary>
    public List<DocumentResult> RelevantDocuments { get; set; } = [];

    /// <summary>
    /// The structured response generated by the FAQ agent.
    /// </summary>
    public FAQAgentResponse? GeneratedResponse { get; set; }

    /// <summary>
    /// Final response text to be sent to the user.
    /// </summary>
    public string FinalResponse { get; set; } = string.Empty;

    /// <summary>
    /// User context information.
    /// </summary>
    public string UserId { get; set; } = string.Empty;

    /// <summary>
    /// Tenant context information.
    /// </summary>
    public string TenantId { get; set; } = string.Empty;

    /// <summary>
    /// Whether user clarification is needed.
    /// </summary>
    public bool NeedsClarification { get; set; }

    /// <summary>
    /// Clarification message if needed.
    /// </summary>
    public string ClarificationMessage { get; set; } = string.Empty;
}